# Generated by Django 4.1.3 on 2022-11-21 09:37

import cloudinary_storage.storage
import cloudinary_storage.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_audio_file_audio_image_audio_transcription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='image',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='transcription',
        ),
        migrations.AddField(
            model_name='audio',
            name='file',
            field=models.ImageField(null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='', validators=[cloudinary_storage.validators.validate_video]),
        ),
        migrations.AlterField(
            model_name='audio',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 9, 37, 30, 206978, tzinfo=datetime.timezone.utc)),
        ),
    ]
