# Generated by Django 4.1.3 on 2022-11-21 10:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_audio_image_remove_audio_transcription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='file',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='message',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='name',
        ),
        migrations.AddField(
            model_name='audio',
            name='clip',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
