# Generated by Django 4.1.3 on 2022-11-21 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_audio_date_created_remove_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 10, 31, 15, 525410, tzinfo=datetime.timezone.utc)),
        ),
    ]
