# Generated by Django 4.1.3 on 2022-11-21 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_audio_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 10, 31, 25, 423973, tzinfo=datetime.timezone.utc)),
        ),
    ]
