# Generated by Django 4.1.3 on 2022-11-22 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_audio_clip_audio_file_audio_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 10, 3, 22, 228520, tzinfo=datetime.timezone.utc)),
        ),
    ]
